// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvwlBtbj289kda2jhJXpPgFfAglE9aEcg',
    appId: '1:22048350424:web:6e5c961e654de0cca8b7ad',
    messagingSenderId: '22048350424',
    projectId: 'e-shop-d9bfc',
    authDomain: 'e-shop-d9bfc.firebaseapp.com',
    storageBucket: 'e-shop-d9bfc.appspot.com',
    measurementId: 'G-5LSF4H1R2L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAkebcoJkDGgFf2cDwTpOBbZY89meETPw',
    appId: '1:22048350424:android:971258667d07043da8b7ad',
    messagingSenderId: '22048350424',
    projectId: 'e-shop-d9bfc',
    storageBucket: 'e-shop-d9bfc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADw-dgTcIufx0EsvmT1htS_SOigeMOG6k',
    appId: '1:22048350424:ios:90d8270d8e5cad61a8b7ad',
    messagingSenderId: '22048350424',
    projectId: 'e-shop-d9bfc',
    storageBucket: 'e-shop-d9bfc.appspot.com',
    iosClientId: '22048350424-a42v70i7qek3b4m1fu3srfnasogntg1m.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADw-dgTcIufx0EsvmT1htS_SOigeMOG6k',
    appId: '1:22048350424:ios:90d8270d8e5cad61a8b7ad',
    messagingSenderId: '22048350424',
    projectId: 'e-shop-d9bfc',
    storageBucket: 'e-shop-d9bfc.appspot.com',
    iosClientId: '22048350424-a42v70i7qek3b4m1fu3srfnasogntg1m.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvwlBtbj289kda2jhJXpPgFfAglE9aEcg',
    appId: '1:22048350424:web:f3022e001eee31a2a8b7ad',
    messagingSenderId: '22048350424',
    projectId: 'e-shop-d9bfc',
    authDomain: 'e-shop-d9bfc.firebaseapp.com',
    storageBucket: 'e-shop-d9bfc.appspot.com',
    measurementId: 'G-LJ86LSF5JR',
  );
}
